version: "3.8"
services:
  test:
    build: .
    command: go test ./tests/...
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/wallet?sslmode=disable
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wallet
