services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wallet
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d # <-- добавлено для автоматического создания таблиц

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/wallet?sslmode=disable
      - PORT=8080
    depends_on:
      - db
    command: ["./wait-for-postgres.sh", "db", "./server"]

volumes:
  db-data:
